//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSource
    {
        public int BusinessSourceID { get; set; }
        public string BusinessSourceName { get; set; }
        public Nullable<int> BusinessSourceAddedBy { get; set; }
        public Nullable<System.DateTime> BusinessSourceAddedDate { get; set; }
        public Nullable<int> BusinessSourceEditedBy { get; set; }
        public Nullable<System.DateTime> BusinessSourceEditedDate { get; set; }
    }
}
