//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CityStateID { get; set; }
        public Nullable<int> CityAddedBy { get; set; }
        public Nullable<System.DateTime> CityAddedDate { get; set; }
        public Nullable<int> CityEditedBy { get; set; }
        public Nullable<System.DateTime> CityEditedDate { get; set; }
        public Nullable<bool> CityIsActive { get; set; }
    
        public virtual State State { get; set; }
    }
}
