//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Folio()
        {
            this.FolioDetails = new HashSet<FolioDetail>();
        }
    
        public int FolioID { get; set; }
        public Nullable<int> FolioHotelID { get; set; }
        public string FolioCode { get; set; }
        public Nullable<int> FolioGuestID { get; set; }
        public Nullable<int> FolioReservationID { get; set; }
        public System.DateTime FolioDateIN { get; set; }
        public System.DateTime FolioDateOUT { get; set; }
        public string FolioNotes { get; set; }
        public Nullable<int> FolioAddedBy { get; set; }
        public Nullable<System.DateTime> FolioAddedDate { get; set; }
        public Nullable<int> FolioEditedBy { get; set; }
        public Nullable<System.DateTime> FolioEditedDate { get; set; }
    
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolioDetail> FolioDetails { get; set; }
    }
}
