//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelAltName { get; set; }
        public string CompanyName { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Registration { get; set; }
        public string TaxID1 { get; set; }
        public string TaxID2 { get; set; }
        public string LogoFileURL { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public Nullable<System.TimeSpan> NextDayCutOff { get; set; }
    }
}
