//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDType
    {
        public int ID { get; set; }
        public string IDName { get; set; }
        public Nullable<int> IDAddedBy { get; set; }
        public Nullable<System.DateTime> IDAddedDate { get; set; }
        public Nullable<int> IDEditedBy { get; set; }
        public Nullable<System.DateTime> IDEditedDate { get; set; }
    }
}
