//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomChargeType
    {
        public int RoomChargeTypeID { get; set; }
        public string RoomChargeTypeName { get; set; }
        public Nullable<int> RoomChargeTypeAddedBy { get; set; }
        public Nullable<System.DateTime> RoomChargeTypeAddedDate { get; set; }
        public Nullable<int> RoomChargeTypeEditedBy { get; set; }
        public Nullable<System.DateTime> RoomChargeTypeEditedDate { get; set; }
        public Nullable<bool> RoomChargeTypeIsActive { get; set; }
    }
}
