//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomStatu()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int RoomStatusID { get; set; }
        public string RoomsStatusName { get; set; }
        public Nullable<int> RoomStatusAddedBy { get; set; }
        public Nullable<System.DateTime> RoomStatusAddedDate { get; set; }
        public Nullable<int> RoomStatusEditedBy { get; set; }
        public Nullable<System.DateTime> RoomStatusEditedDate { get; set; }
        public Nullable<bool> RoomStatusIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
