//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomRate()
        {
            this.FolioDetails = new HashSet<FolioDetail>();
        }
    
        public int RoomRateID { get; set; }
        public Nullable<int> RoomRateHotelID { get; set; }
        public string RoomRateCode { get; set; }
        public string RoomRateDescription { get; set; }
        public Nullable<int> RoomRateRoomTypeID { get; set; }
        public Nullable<System.DateTime> RoomRateDateStart { get; set; }
        public Nullable<System.DateTime> RoomRateDateEnd { get; set; }
        public Nullable<int> RoomRateMinNights { get; set; }
        public Nullable<int> RoomRateMaxNights { get; set; }
        public Nullable<int> RoomRateMinPerson { get; set; }
        public Nullable<int> RoomRateMaxPerson { get; set; }
        public Nullable<bool> RoomRateIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FolioDetail> FolioDetails { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
