//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salutation
    {
        public int SalutationID { get; set; }
        public string SalutationDescription { get; set; }
        public Nullable<bool> SalutationIsActive { get; set; }
    }
}
