//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserType()
        {
            this.Users = new HashSet<User>();
        }
    
        public int UserTypeId { get; set; }
        public string UserType1 { get; set; }
        public Nullable<bool> UserIsActive { get; set; }
        public Nullable<int> UserAddedBy { get; set; }
        public Nullable<System.DateTime> UserAddedDate { get; set; }
        public Nullable<int> UserEditedBy { get; set; }
        public Nullable<System.DateTime> UserEditedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
