//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cronus.HotelMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserPasswordSalt { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserMiddleName { get; set; }
        public int UserTypeId { get; set; }
        public string UserToken { get; set; }
        public Nullable<int> UserAddedBy { get; set; }
        public Nullable<System.DateTime> UserAddedDate { get; set; }
        public Nullable<int> UserEditedBy { get; set; }
        public Nullable<System.DateTime> UserEditedDate { get; set; }
        public string UserStatus { get; set; }
        public Nullable<long> UserIsActive { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
